### ISSUE TITLE
toFile saves empty images

### ISSUE THREAD

**Issue by JoseMorango** [typpo/quickchart-php#7]
Using the  $qc->toFile('tmp/chart.png')  saves empty images, cannot get any real chart image, always returns a 0 bytes image

**Comment by typpo** [comment]
This can happen when curl silently errors.  The most likely explanation for this is that you have an outdated root certificate.  To fix, you must update your local CA bundle.

The root cause of this is that a root certificate `IdentTrust DST Root CA X3` expired.  Those with outdated systems still have this certificate.

 - [Learn more here](https://scotthelme.co.uk/lets-encrypt-old-root-expiration/)
 - [Relevant news article](https://techcrunch.com/2021/09/21/lets-encrypt-root-expiry/?guccounter=1)

b42b81d updates the library to throw an error when curl errors. This update is included in v1.1.4
